Removed extraneous properties from config file
simeoncloud/Baseline pull request #18
Opened 2022-01-10 00:15 UTC by david-simeon

2022-01-10 00:35 UTC, rdorta-simeon approved these changes

2022-01-16 19:27 UTC, jeff-simeon submitted a review, later dismissed

2022-01-17 15:34 UTC, rdorta-simeon requested changes
TenantShortName? Where is that coming from?

2022-01-18 17:35 UTC, jeff-simeon approved these changes

2022-01-18 21:08 UTC, merged