feature/put_back_AtpPolicyForO365_desc
simeoncloud/Baseline pull request #29
Opened 2022-02-17 00:29 UTC by dawit-simeon

2022-02-17 00:30 UTC, rdorta-simeon submitted a review, later dismissed

2022-02-17 00:31 UTC, jeff-simeon requested changes

2022-02-17 00:31 UTC, jeff-simeon commented on Source/Resources/Content/PowerShell/ExchangeOnline/AtpPolicyForO365/Configuration.json
> +  "description": "| What does this do? | Defines Azure Active Directory authorization settings. The baseline allows users to sign up for email based subscriptions, use Self-Serve Password Reset, and
should be $description

2022-02-17 00:32 UTC, dawit-simeon commented on Source/Resources/Content/PowerShell/ExchangeOnline/AtpPolicyForO365/Configuration.json
> +  "description": "| What does this do? | Defines Azure Active Directory authorization settings. The baseline allows users to sign up for email based subscriptions, use Self-Serve Password Reset, and
good catch

2022-02-17 00:36 UTC, jeff-simeon approved these changes

2022-03-11 00:02 UTC, david-simeon commented
Fixed in a diff PR. This is a zombie PR.

2022-03-11 00:07 UTC, rdorta-simeon approved these changes

2022-03-11 00:09 UTC, merged