SD-1931 Migrate company branding from AADIAM to MSGraph
simeoncloud/Baseline pull request #88
Opened 2023-09-05 21:18 UTC by bd-ldumer

2023-09-06 00:30 UTC, jeff-simeon commented on Source/Resources/Content/MSGraph/Organization/Configuration.json
> +  "$description": "| What does this do? | Defines the messages and logos shown to users on Azure login screens. The baseline automatically populates the username watermark with \"user@yourcompanyname
please delete the json for the replaced provider

2023-09-07 12:49 UTC, rdorta-simeon requested changes
Remove the json for the provider that was removed

2023-10-09 17:09 UTC, rdorta-simeon approved these changes

2023-10-09 17:12 UTC, jeff-simeon approved these changes

2023-10-09 20:32 UTC, david-simeon approved these changes

2023-10-09 20:39 UTC, merged